#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get emoncms/user
user=$RET

chown -R $user "<root_dir>/Modules/device"

#DEBHELPER#

php -f "<root_dir>/scripts/admin/database_update.php"
php -f "<root_dir>/scripts/admin/device_update.php"

exit 0
