#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

case "$1" in
    purge)
        db_get emoncms/mysql_database
        mysql_database_value=$RET

        db_get emoncms/mysql_timeseries
        mysql_timeseries_value=$RET

        db_get emoncms/mysql_user
        mysql_user_value=$RET

        mysql -uroot -e "DROP DATABASE IF EXISTS $mysql_database_value;"
        mysql -uroot -e "DROP DATABASE IF EXISTS $mysql_timeseries_value;"
        mysql -uroot -e "DROP USER IF EXISTS '$mysql_user_value'@'localhost';"
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
