#!/usr/bin/env sh

test -x /usr/sbin/logrotate || exit 0
/usr/sbin/logrotate -v -s /var/log/logrotate/logrotate.status /etc/logrotate.CUSTOM 2>&1 | tee /var/log/logrotate/logrotate.log

systemctl reload log2ram

