#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get emoncms/user
if [ ! -z "$RET" ]; then
    user=$RET
else
    user="root"
fi

php -f "<root_dir>/scripts/database_update.php"

chown -R $user "<root_dir>/Modules/app"

#DEBHELPER#

exit 0
