#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get emoncms/user
user=$RET

chown -R $user "<root_dir>/Modules/graph"

#DEBHELPER#

php -f "<root_dir>/scripts/admin/database_update.php" > /dev/null 2>&1

exit 0
