#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

settings_file=<root_dir>/settings.ini

if cat /proc/device-tree/model | grep -q "Raspberry"; then
    db_set emoncms/user "pi"
    db_input medium emoncms/user || true
else
    db_input high emoncms/user || true
fi
db_input $smtp_prio emoncms/smtp || true
db_go || true

db_get emoncms/smtp
smtp_enable=$RET

if [ "$smtp_enable" = "true" ]; then
    if [ -f "$settings_file" ]; then
        smtp_addr_key="from_email"
        smtp_addr_value=`grep -A6 -P '^\[smtp\]$' $settings_file | grep -m1 "$smtp_addr_key.*=" |\
                         sed "s/${smtp_addr_key}.*=//" | sed -r "s/\s+//g" | sed "s/^'//;s/'$//"`
        if [ -n "$smtp_addr_value" ] && [ "$smtp_addr_value" != "SMTP_ADDR" ]; then
            db_set emoncms/smtp_email_addr "$smtp_addr_value"
        fi

        smtp_name_key="from_name"
        smtp_name_value=`grep -A6 -P '^\[smtp\]$' $settings_file | grep -m1 "$smtp_name_key.*=" |\
                         sed "s/${smtp_name_key}.*=//" | sed -r "s/\s+//g" | sed "s/^'//;s/'$//"`
        if [ -n "$smtp_name_value" ] && [ "$smtp_name_value" != "SMTP_NAME" ]; then
            db_set emoncms/smtp_email_name "$smtp_name_value"
        fi

        smtp_host_key="host"
        smtp_host_value=`grep -A6 -P '^\[smtp\]$' $settings_file | grep -m1 "$smtp_host_key.*=" |\
                         sed "s/${smtp_host_key}.*=//" | sed -r "s/\s+//g" | sed "s/^'//;s/'$//"`
        if [ -n "$smtp_host_value" ] && [ "$smtp_host_value" != "SMTP_HOST" ]; then
            db_set emoncms/smtp_host "$smtp_host_value"
        fi

        smtp_port_key="port"
        smtp_port_value=`grep -A6 -P '^\[smtp\]$' $settings_file | grep -m1 "$smtp_port_key.*=" |\
                         sed "s/${smtp_port_key}.*=//" | sed -r "s/\s+//g" | sed "s/^'//;s/'$//"`
        if [ -n "$smtp_port_value" ] && [ "$smtp_port_value" != "SMTP_PORT" ]; then
            db_set emoncms/smtp_port "$smtp_port_value"
        fi

        smtp_user_key="username"
        smtp_user_value=`grep -A6 -P "^\[smtp\]$" $settings_file | grep -m1 "$smtp_user_key.*=" |\
                         sed "s/${smtp_user_key}.*=//" | sed -r "s/\s+//g" | sed "s/^'//;s/'$//"`
        if [ -n "$smtp_user_value" ] && [ "$smtp_user_value" != "SMTP_USER" ]; then
            db_set emoncms/smtp_user "$smtp_user_value"
        fi

        smtp_password_key="password"
        smtp_password_value=`grep -A6 -P "^\[smtp\]$" $settings_file | grep -m1 "$smtp_password_key.*=" |\
                             sed "s/${smtp_password_key}.*=//" | sed -r "s/\s+//g" | sed "s/^'//;s/'$//"`
        if [ -n "$smtp_password_value" ] && [ "$smtp_password_value" != "SMTP_PASSWORD" ]; then
            db_set emoncms/smtp_password "$smtp_password_value"
        fi
    fi
    db_input high emoncms/smtp_host || true
    db_input high emoncms/smtp_port || true

    db_input high emoncms/smtp_user || true
    db_input high emoncms/smtp_password || true

    db_input high emoncms/smtp_email_addr || true
    db_input high emoncms/smtp_email_name || true
    db_go || true
fi
