#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

if cat /proc/device-tree/model | grep -q "Raspberry"; then
    db_input medium || true
    db_set emoncms/user "pi"
else
    db_input high || true
fi
db_go || true 