#!/bin/sh
set -e

case "$1" in
    purge)
        if [ -d <data_dir> ]; then
            rm -r <data_dir>
        fi
        if [ -d <log_dir> ]; then
            rm -r <log_dir>
        fi
        if [ -d <root_dir> ]; then
            rm -r <root_dir> 
        fi
        ;;
    *)
        ;;
esac
case "$1" in
    remove | purge)
        if [ -e /var/www/emoncms ]; then
            rm -rf /var/www/emoncms
        fi
        if [ -e /var/www/html/emoncms ]; then
            rm -rf /var/www/html/emoncms
        fi
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
