#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

root_dir="<root_dir>"
data_dir="<data_dir>"
log_dir="<log_dir>"

db_get emoncms/user
if [ ! -z "$RET" ]; then
    user=$RET
else
    user="root"
fi

# Create emoncms logfolder
if [ ! -d $log_dir ]; then
    mkdir $log_dir
	chown $user $log_dir
	touch "$log_dir/emoncms.log"
    chmod 666 "$log_dir/emoncms.log"
fi

#Create date main directory
if [ ! -d $data_dir ]; then
	mkdir -p $data_dir 
fi

# Create data directories for emoncms feed engines:
for engine in "mysql" "phpfina" "phptimeseries"; do
    if [ ! -d $data_dir/$engine ]; then
        mkdir $data_dir/$engine
        chown www-data:root $data_dir/$engine
    fi
done

#Symbolic Link 
if [ ! -d /var/www/html/emoncms ]; then
    ln -s $root_dir /var/www/html/emoncms
	if [ -f /var/www/html/index.html ]; then
        rm /var/www/html/index.html
    fi
fi

if [ ! -d "/var/www/emoncms" ]; then
    ln -s $root_dir /var/www/emoncms
fi

sed -i "/OPENENERGYMONITOR_DIR/d" 	         $root_dir/settings.ini
sed -i "/EMONCMS_DIR/d"                      $root_dir/settings.ini
sed -i '1{/^$/d}'                            $root_dir/settings.ini

sed -i "s~EMONCMS_DATADIR~$data_dir~" $root_dir/settings.ini

if ! grep -q "\[smtp\]$" $root_dir/settings.ini ; then
    echo "\n[smtp]" >> $root_dir/settings.ini
	echo "host = 'SMTP_HOST'" >> $root_dir/settings.ini
	echo "from_email = 'SMTP_ADDR'" >> $root_dir/settings.ini
	echo "from_name = 'SMTP_NAME'" >> $root_dir/settings.ini
	echo "username = 'SMTP_USER'" >> $root_dir/settings.ini
	echo "password = 'SMTP_PASSWORD'" >> $root_dir/settings.ini
fi

if ! grep -q "enable_update_ui"              $root_dir/settings.ini; then
    sed -i '/enable_admin_ui.*/a\
enable_update_ui = false'                    $root_dir/settings.ini
fi

#Give Pi the Diretory of emoncms
chown -R $user $root_dir

#DEBHELPER#

exit 0
