#!/bin/sh
set -e

case "$1" in
    remove)
        if [ -d /lib/systemd/system/feedwriter.service.d ]; then
            rm -rf /lib/systemd/system/feedwriter.service*
        fi
        if [ -d /lib/systemd/system/service-runner.service.d ]; then
            rm -rf /lib/systemd/system/service-runner.service*
        fi
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
