#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get emoncms/user
user=$RET

case "$1" in
    install | configure)
        # Disable redis persistance
        sed -i "s/^save 900 1/#save 900 1/" /etc/redis/redis.conf
        sed -i "s/^save 300 1/#save 300 1/" /etc/redis/redis.conf
        sed -i "s/^save 60 1/#save 60 1/" /etc/redis/redis.conf
        systemctl restart redis-server

        if [ ! -d /lib/systemd/system/feedwriter.service.d ]; then
            mkdir /lib/systemd/system/feedwriter.service.d
        fi
        echo '[Service]\nEnvironment="USER='$user'"' > /lib/systemd/system/feedwriter.service.d/feedwriter.conf

        if [ ! -f /lib/systemd/system/feedwriter.service ]; then
            ln -s <root_dir>/scripts/services/feedwriter/feedwriter.service /lib/systemd/system
            systemctl enable feedwriter.service
            systemctl start feedwriter.service
        fi


        if [ ! -d /lib/systemd/system/service-runner.service.d ]; then
            mkdir /lib/systemd/system/service-runner.service.d
        fi
        echo '[Service]\nUser='$user > /lib/systemd/system/service-runner.service.d/service-runner.conf

        if [ ! -f /lib/systemd/system/service-runner.service ]; then
            ln -s <root_dir>/scripts/services/service-runner/service-runner.service /lib/systemd/system
            systemctl enable service-runner.service
            systemctl start service-runner.service
        fi


        # Reload webserver, to enable freshly installed PHP dependency
        # TODO: find out which webserver was actually used
        systemctl reload apache2
        ;;
    upgrade)
        systemctl daemon-reload
        systemctl restart feedwriter.service
        systemctl restart service-runner.service
        ;;
    *)
        ;;
esac

#DEBHELPER#

exit 0
