#!/bin/sh
set -e

mqtt_user=emonmqtt
mqtt_password=emonmqtt
root_dir="<root_dir>"

# Disable mosquitto persistance
sed -i "s/^persistence true/persistence false/" /etc/mosquitto/mosquitto.conf
# append line: allow_anonymous false
sed -i -n '/allow_anonymous false/!p;$a allow_anonymous false' /etc/mosquitto/mosquitto.conf
# append line: password_file /etc/mosquitto/passwd
sed -i -n '/password_file \/etc\/mosquitto\/passwd/!p;$a password_file \/etc\/mosquitto\/passwd' /etc/mosquitto/mosquitto.conf
# append line: log_type error
sed -i -n '/log_type error/!p;$a log_type error' /etc/mosquitto/mosquitto.conf

# Create mosquitto password file
touch /etc/mosquitto/passwd
mosquitto_passwd -b /etc/mosquitto/passwd $mqtt_user $mqtt_password

pecl install Mosquitto-beta

# Add mosquitto to php mods available
PHP_VER=$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d"." )
printf "extension=mosquitto.so" | tee /etc/php/$PHP_VER/mods-available/mosquitto.ini 1>&2
phpenmod mosquitto

#emoncms-core-script
servicepath=$root_dir/scripts/services/emoncms_mqtt/emoncms_mqtt.service
$root_dir/common/install_emoncms_service.sh $servicepath emoncms_mqtt


if [ ! -d /lib/systemd/system/emoncms_mqtt.service.d ]; then
    mkdir /lib/systemd/system/emoncms_mqtt.service.d
fi
echo $'[Service]\nEnvironment="USER='$user'"' > emoncms_mqtt.conf
mv emoncms_mqtt.conf /lib/systemd/system/emoncms_mqtt.service.d/emoncms_mqtt.conf
	
systemctl daemon-reload
systemctl restart emoncms_mqtt.service

#DEBHELPER#

exit 0
