#!/bin/sh
set -e

#DEBHELPER#

case "$1" in
    install | configure)
        sed -i "s/^CustomLog/#CustomLog/" /etc/apache2/conf-available/other-vhosts-access-log.conf

        # Enable apache mod rewrite
        a2enmod -q rewrite

        # Default apache2 configuration
        a2enconf -q emoncms.conf

        # Configure virtual host
        if [ -f /etc/apache2/sites-enabled/000-default.conf ]; then
            a2dissite -q 000-default.conf
        fi
        a2ensite -q emoncms.conf

        systemctl restart apache2
        ;;
    *)
        systemctl reload apache2
        ;;
esac

exit 0
