#!/bin/bash

# Script to update new emonPi's to latest firmware and software the fist time they are booted up in the factory
# Looks to see if /var/log/emoncms/emonpiupdate.log exists or LCD push button (GPIO 23) is pressed (high when pressed)

# To rc.local before exit 0 add:
# su pi -c '/opt/openenergymonitor/EmonScripts/update/firstbootupdate'

# Check if update log file is empty if so then proceed to update

if [ ! -s /var/log/emoncms/update.log ]; then
	echo "First Boot Update.."
	sleep 5
	printf "Checking internet connectivity..,\n"
	WGET="/usr/bin/wget"
	$WGET -q --tries=20 --timeout=5 http://www.google.com -O /tmp/google.idx &> /dev/null
	if [ ! -s /tmp/google.idx ]; then
		echo "No Internet connection :-("
	else
 		echo "Internet connection detected running update.."
 		connected=true
	fi

	if [ "$connected" = true ]; then
    /opt/openenergymonitor/EmonScripts/update/service-runner-update.sh all emonpi 2>&1 >> /var/log/emoncms/update.log 2>&1
    # set permissions on newly created logfile
    sudo chmod 666 /var/log/emoncms/update.log
	fi
else
	echo "Not first boot"
	exit
fi

exit
