#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get emoncms/user
user=$RET

chown -R $user "/var/opt/emonmuc"
chown -R $user "<root_dir>/Modules/muc"
chown -R $user "<root_dir>/Modules/channel"

#DEBHELPER#

php -f "<root_dir>/scripts/admin/database_update.php" > /dev/null 2>&1
php -f "<root_dir>/scripts/admin/device_update.php"

exit 0
