#!/bin/sh
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_get emoncms/user
if [ ! -z "$RET" ]; then
    user=$RET
else
    user="root"
fi

php -f "<root_dir>/scripts/database_update.php"
php -f "<root_dir>/scripts/emonmucdevupdate.php"

chown -R $user "<root_dir>/Modules/muc"
chown -R $user "<root_dir>/Modules/channel"
chown -R $user "<root_dir>/Theme/seal"

#DEBHELPER#

exit 0
